name: plausible_analytics
description: A Flutter plugin for Plausible Analytics. This uses the events API to send clickevents and goals to Plausible Analytics.
version: 0.2.1
homepage: https://github.com/bostrot/flutter_plausible_analytics.git
issue_tracker: https://github.com/bostrot/flutter_plausible_analytics/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
   universal_io: ^2.0.4
   device_info_plus: ^4.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
